name: 'Pull Request Workflow Cancel'
description: 'Cancel stale workflow runs for the current pull-request'
inputs:
  workflows:
    description: 'Filenames of the workflows to check, separated by a pipe |'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: check-circle
  color: red
