name: Pull Request Workflow Cancel Second Example
on: [pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running something else now'
      - run: sleep 60
      - run: echo 'wasnt cancelled'
